spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          clientRegisteredEvent:ge.notificationservice.dto.ClientRegisteredEvent,
          doctorRegisteredEvent:ge.notificationservice.dto.DoctorRegisteredEvent
      




  mail:
    username: healthbridge64@gmail.com
    password: mfvl bjmv cnws ldtc
    port: 587
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8000


